a=int(input("enter the value: "))
b=int(input("enter the value: "))
c=int(input("enter the value: ")) 
d=int(input("enter the value: "))
e=int(input("enter the value: "))
f=int(input("enter the value: "))
g=int(input("enter the value: "))
h=int(input("enter the value: "))
i=int(input("enter the value: "))
j=int(input("enter the value: "))
print(a+b+c+d+e+f+g+h+i+j)
print(a-b-c-d-e-f-g-h-i-j)
print(a/b+c/d+e/f+g/h+i/j)
#python version :3 
x=int(input(17/2%2*3**3))
a1=int(input(" "))
a2=int(input(" "))
a1,a2=a2,a2
print(a1+a2)
